parameters:
  calculation_method:
    type: enum
    default: percentage_of_tracked
    required: true
    description: 트레일링 스탑 계산 방식 (평단가%p/진입가%p/정적차이/극값비율%)
    allowed:
    - average_price_percent
    - entry_price_percent
    - static_value_offset
    - percentage_of_tracked
  trail_direction:
    type: enum
    default: up
    required: true
    description: '트레일링 방향 (UP: 고점추적→하락신호, DOWN: 저점추적→상승신호)'
    allowed:
    - up
    - down
  value:
    type: decimal
    default: '-2.0'
    required: true
    description: '계산에 사용될 값 (퍼센트: -2.0=-2%, 원화: 1000=1000원)'
    min: '-50.0'
    max: '50.0'
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
