parameters:
  band_position:
    type: enum
    default: 상단
    required: true
    description: 비교할 볼린저밴드 위치
    allowed:
    - \uc0c1\ub2e8
    - \uc911\uc559\uc120
    - \ud558\ub2e8
  period:
    type: integer
    default: '20'
    required: true
    description: 볼린저밴드 이동평균 기간
    min: '5'
    max: '100'
  std_dev:
    type: decimal
    default: '2.0'
    required: true
    description: 볼린저밴드 표준편차 배수
    min: '1.0'
    max: '3.0'
  timeframe:
    type: enum
    default: position_follow
    required: true
    description: 봉 단위 시간
    allowed:
    - position_follow
    - 1m
    - 3m
    - 5m
    - 10m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    - 1w
    - 1M
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
