# ═══════════════════════════════════════════════════════════════
# 🎯 META_TRAILING_STOP (트레일링 스탑) - 매개변수 정의
# ═══════════════════════════════════════════════════════════════
# 대응 테이블: tv_variable_parameters
# 지표 ID: META_TRAILING_STOP
# ═══════════════════════════════════════════════════════════════

# 매개변수 목록
parameters:
  # ─────────────────────────────────────────────────────────────
  # 📊 계산 방식 (Calculation Method) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  calculation_method:
    # 기본 정보
    parameter_name: "calculation_method"
    parameter_type: "enum"
    default_value: "percentage_of_tracked"
    is_required: true

    # 선택 옵션
    enum_values:
      - "average_price_percent"      # 평단값 퍼센트포인트 (%p) - 평단가 기준
      - "entry_price_percent"        # 진입값 퍼센트포인트 (%p) - 진입가 기준
      - "static_value_offset"        # 정적차이 (원화/수치) - 절대값 차이
      - "percentage_of_tracked"      # 극값 비율퍼센트 (%) - 최고/최저점 대비

    # 표시 정보
    display_name_ko: "계산 방식"
    display_name_en: "Calculation Method"
    description: "트레일링 스탑 계산 방식 (평단가%p/진입가%p/정적차이/극값비율%)"
    display_order: 1

    # UI 매핑 (한국어 표시용)
    display_mapping:
      "average_price_percent": "평단값 퍼센트포인트 (%p)"
      "entry_price_percent": "진입값 퍼센트포인트 (%p)"
      "static_value_offset": "정적차이 (원화/수치)"
      "percentage_of_tracked": "극값 비율퍼센트 (%)"

    # 추가 속성
    validation_rules:
      - "must_be_valid_enum_value"

    recommended_values:
      conservative: ["percentage_of_tracked"]
      aggressive: ["entry_price_percent", "average_price_percent"]

  # ─────────────────────────────────────────────────────────────
  # 💰 계산값 (Value) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  value:
    # 기본 정보
    parameter_name: "value"
    parameter_type: "decimal"
    default_value: "-2.0"
    is_required: true

    # 제약 조건
    min_value: "-50.0"
    max_value: "50.0"

    # 표시 정보
    display_name_ko: "계산값"
    display_name_en: "Value"
    description: "계산에 사용될 값 (퍼센트: -2.0=-2%, 원화: 1000=1000원)"
    display_order: 2

    # 추가 속성
    validation_rules:
      - "must_be_decimal"
      - "within_range_minus50_to_50"

    recommended_values:
      conservative: [-1.0, -2.0, -3.0]
      moderate: [-3.0, -5.0, -7.0]
      aggressive: [-7.0, -10.0, -15.0]

    context_specific:
      crypto:
        popular: [-2.0, -3.0, -5.0]
        scalping: [-0.5, -1.0, -1.5]
      stocks:
        popular: [-3.0, -5.0, -7.0]
        swing: [-5.0, -7.0, -10.0]

  # ─────────────────────────────────────────────────────────────
  # 🎯 추적 방향 (Trail Direction) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  trail_direction:
    # 기본 정보
    parameter_name: "trail_direction"
    parameter_type: "enum"
    default_value: "up"
    is_required: true

    # 선택 옵션
    enum_values:
      - "up"      # 상향 추적 (고점 추적, 하락 시 신호)
      - "down"    # 하향 추적 (저점 추적, 상승 시 신호)

    # 표시 정보
    display_name_ko: "추적 방향"
    display_name_en: "Trail Direction"
    description: "트레일링 방향 (UP: 고점추적→하락신호, DOWN: 저점추적→상승신호)"
    display_order: 3

    # UI 매핑 (한국어 표시용)
    display_mapping:
      "up": "상향 추적 (고점 추적)"
      "down": "하향 추적 (저점 추적)"

    # 추가 속성
    validation_rules:
      - "must_be_valid_enum_value"

    recommended_combinations:
      long_position:
        direction: ["up"]
        description: "매수 포지션에는 상향 추적 권장"
      short_position:
        direction: ["down"]
        description: "매도 포지션에는 하향 추적 권장"

# ─────────────────────────────────────────────────────────────
# 📝 매개변수 조합 규칙
# ─────────────────────────────────────────────────────────────
parameter_validation:
  # 조합 규칙
  combination_rules:
    - name: "value_direction_consistency"
      description: "값과 방향의 일관성 확인"
      rule: "if trail_direction == 'up' then value should be negative for stop loss"

    - name: "calculation_method_value_range"
      description: "계산 방식에 따른 값 범위 검증"
      rule: "if calculation_method in ['percentage_of_tracked', 'average_price_percent', 'entry_price_percent'] then abs(value) <= 50"

  # 경고 조건
  warnings:
    - condition: "abs(value) < 0.5"
      message: "너무 작은 값은 빈번한 신호를 발생시킬 수 있습니다"

    - condition: "abs(value) > 20"
      message: "너무 큰 값은 트레일링 효과가 제한될 수 있습니다"

    - condition: "calculation_method == 'static_value_offset' and abs(value) < 100"
      message: "정적차이 모드에서는 충분히 큰 값을 권장합니다"

# ─────────────────────────────────────────────────────────────
# 🎨 UI 표시 설정
# ─────────────────────────────────────────────────────────────
ui_settings:
  parameter_layout: "vertical"  # vertical, horizontal, grid

  calculation_method:
    widget_type: "combobox"
    group_separator: true
    groups:
      basic: ["percentage_of_tracked", "entry_price_percent"]
      advanced: ["average_price_percent", "static_value_offset"]

  value:
    widget_type: "spinbox"
    step_size: 0.1
    decimal_places: 1
    quick_buttons: [-1.0, -2.0, -3.0, -5.0, -10.0]

  trail_direction:
    widget_type: "radiobutton"
    layout: "horizontal"
    icons:
      up: "⬆️"
      down: "⬇️"
