parameters:
  fast_period:
    type: integer
    default: '12'
    required: true
    description: MACD 빠른 이동평균 기간
    min: '5'
    max: '50'
  macd_type:
    type: enum
    default: MACD선
    required: true
    description: 'MACD선: 빠른선-느린선, 시그널선: MACD의 이평, 히스토그램: MACD-시그널'
    allowed:
    - MACD\uc120
    - \uc2dc\uadf8\ub110\uc120
    - \ud788\uc2a4\ud1a0\uadf8\ub7a8
  signal_period:
    type: integer
    default: '9'
    required: true
    description: MACD 시그널선 기간
    min: '5'
    max: '20'
  slow_period:
    type: integer
    default: '26'
    required: true
    description: MACD 느린 이동평균 기간
    min: '10'
    max: '100'
  timeframe:
    type: enum
    default: position_follow
    required: true
    description: 봉 단위 시간
    allowed:
    - position_follow
    - 1m
    - 3m
    - 5m
    - 10m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    - 1w
    - 1M
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
