# ═══════════════════════════════════════════════════════════════
# 📈 SMA (단순이동평균) - 매개변수 정의
# ═══════════════════════════════════════════════════════════════
# 대응 테이블: tv_variable_parameters
# 지표 ID: SMA
# ═══════════════════════════════════════════════════════════════

# 매개변수 목록
parameters:
  # ─────────────────────────────────────────────────────────────
  # 📅 기간 (Period) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  period:
    # 기본 정보
    parameter_name: "period"
    parameter_type: "integer"
    default_value: "20"
    is_required: true
    
    # 제약 조건
    min_value: "1"
    max_value: "240"
    
    # 표시 정보
    display_name_ko: "기간"
    display_name_en: "Period"
    description: "단기: 5,10,20 / 중기: 60,120 / 장기: 200,240"
    display_order: 1
    
    # 추가 속성
    validation_rules:
      - "must_be_positive_integer"
      - "within_range_1_to_240"
    
    recommended_values:
      short_term: [5, 10, 20]
      medium_term: [50, 60, 120]
      long_term: [200, 240]
      
    market_specific:
      crypto:
        popular: [20, 50, 200]
        scalping: [5, 10, 15]
      stocks:
        popular: [20, 50, 200]
        swing: [10, 20, 50]
      forex:
        popular: [14, 21, 55]
        
  # ─────────────────────────────────────────────────────────────
  # ⏰ 타임프레임 (Timeframe) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  timeframe:
    # 기본 정보
    parameter_name: "timeframe"
    parameter_type: "enum"
    default_value: "position_follow"
    is_required: true
    
    # 선택 옵션 (영문 API 형식)
    enum_values:
      - "position_follow"
      - "1m"
      - "3m"
      - "5m"
      - "10m"
      - "15m"
      - "30m"
      - "1h"
      - "4h"
      - "1d"
      - "1w"
      - "1M"
    
    # 표시 정보
    display_name_ko: "타임프레임"
    display_name_en: "Timeframe"
    description: "봉 단위 시간 (전략 기본값 사용 시 무시)"
    display_order: 2
    
    # UI 매핑 (한국어 표시용)
    display_mapping:
      "position_follow": "포지션 설정 따름"
      "1m": "1분"
      "3m": "3분"
      "5m": "5분"
      "10m": "10분"
      "15m": "15분"
      "30m": "30분"
      "1h": "1시간"
      "4h": "4시간"
      "1d": "1일"
      "1w": "1주"
      "1M": "1개월"
      
    # 권장 조합
    recommended_combinations:
      scalping:
        timeframes: ["1m", "3m", "5m"]
        periods: [9, 15, 21]
      swing_trading:
        timeframes: ["15m", "1h", "4h"]
        periods: [20, 50]
      position_trading:
        timeframes: ["1d", "1w"]
        periods: [50, 200]

# ─────────────────────────────────────────────────────────────
# 📝 매개변수 조합 규칙
# ─────────────────────────────────────────────────────────────
parameter_validation:
  # 조합 규칙
  combination_rules:
    - name: "period_timeframe_balance"
      description: "짧은 타임프레임에는 긴 기간 비추천"
      rule: "if timeframe in ['1m', '3m', '5m'] then period <= 50"
      
    - name: "long_term_validation"
      description: "장기 기간은 일봉 이상 권장"
      rule: "if period >= 100 then timeframe in ['1d', '1w', '1M']"
      
  # 경고 조건
  warnings:
    - condition: "period < 5"
      message: "너무 짧은 기간은 노이즈가 많을 수 있습니다"
      
    - condition: "period > 200"
      message: "너무 긴 기간은 신호가 매우 늦을 수 있습니다"
      
    - condition: "timeframe == '1m' and period > 30"
      message: "1분봉에서 긴 기간은 데이터 부족 위험"

# ─────────────────────────────────────────────────────────────
# 🎨 UI 표시 설정
# ─────────────────────────────────────────────────────────────
ui_settings:
  parameter_layout: "vertical"  # vertical, horizontal, grid
  
  period:
    widget_type: "spinbox"
    step_size: 1
    quick_buttons: [5, 10, 20, 50, 100, 200]
    
  timeframe:
    widget_type: "combobox"
    group_separator: true
    groups:
      basic: ["position_follow"]
      short_term: ["1m", "3m", "5m", "10m", "15m"]
      medium_term: ["30m", "1h", "4h"]
      long_term: ["1d", "1w", "1M"]
