# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
# π― META_PYRAMID_TARGET (ν”ΌλΌλ―Έλ”©) - λ§¤κ°λ³€μ μ •μ
# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
# λ€μ‘ ν…μ΄λΈ”: tv_variable_parameters
# μ§€ν‘ ID: META_PYRAMID_TARGET
# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•

# λ§¤κ°λ³€μ λ©λ΅ - UnifiedParameter μ§€μ› κµ¬μ΅°
parameters:
  # β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
  # π― UnifiedParameter κµ¬μ΅° - μ™Έλ¶€ μ μ–΄ν• μƒνƒ λ³€μ μ§€μ›
  # β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ κ³„μ‚° λ°©μ‹ (Calculation Method) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "calculation_method"
    type: "enum"
    default_value: "entry_price_percent"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "average_price_percent"      # ν‰λ‹¨κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p) - ν‰λ‹¨κ°€ κΈ°μ¤€
      - "entry_price_percent"        # μ§„μ…κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p) - μ§„μ…κ°€ κΈ°μ¤€
      - "static_value_offset"        # μ •μ μ°¨μ΄ (μ›ν™”/μμΉ) - μ λ€κ°’ μ°¨μ΄
      - "percentage_of_tracked"      # κ·Ήκ°’ λΉ„μ¨νΌμ„ΌνΈ (%) - μµκ³ /μµμ €μ  λ€λΉ„
    display_name: "κ³„μ‚° λ°©μ‹"
    description: "ν”ΌλΌλ―Έλ”© κ³„μ‚° λ°©μ‹ (ν‰λ‹¨κ°€%p/μ§„μ…κ°€%p/μ •μ μ°¨μ΄/κ·Ήκ°’λΉ„μ¨%)"
    display_order: 1

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ μ¶”μ  κΈ°λ³Έλ³€μ (Tracked Variable) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "tracked_variable"
    type: "enum"
    default_value: "CURRENT_PRICE"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "CURRENT_PRICE"     # ν„μ¬κ°€ (μ‹¤μ‹κ°„)
      - "RSI"               # RSI μ§€ν‘
      - "MACD"              # MACD μ§€ν‘
      - "BOLLINGER_UPPER"   # λ³Όλ¦°μ € μƒλ‹¨
      - "BOLLINGER_LOWER"   # λ³Όλ¦°μ € ν•λ‹¨
      - "SMA_20"            # 20μΌ λ‹¨μμ΄ν‰μ„ 
      - "EMA_12"            # 12μΌ μ§€μμ΄ν‰μ„ 
    display_name: "μ¶”μ  κΈ°λ³Έλ³€μ"
    description: "ν”ΌλΌλ―Έλ”© κΈ°μ¤€μ΄ λ  κΈ°λ³Έ λ³€μ μ„ νƒ (ν„μ¬κ°€, μ§€ν‘ λ“±)"
    display_order: 2

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # οΏ½ κ³„μ‚°κ°’ (Value) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "value"
    type: "decimal"
    default_value: "5.0"
    required: true
    min_value: "-50.0"
    max_value: "100.0"
    enum_values: null
    display_name: "κ³„μ‚°κ°’"
    description: "κ³„μ‚°μ— μ‚¬μ©λ  κ°’ (νΌμ„ΌνΈ: 5.0=5% μμµ, μ›ν™”: 1000=1000μ›)"
    display_order: 3

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π― μ¶”μ  λ°©ν–¥ (Trail Direction) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "trail_direction"
    type: "enum"
    default_value: "up"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "up"      # μƒν–¥ μ¶”μ  (λ¶νƒ€κΈ° - μμµ μ‹ μ¶”κ°€ λ§¤μ)
      - "down"    # ν•ν–¥ μ¶”μ  (λ¬Όνƒ€κΈ° - μ†μ‹¤ μ‹ μ¶”κ°€ λ§¤μ)
    display_name: "μ¶”μ  λ°©ν–¥"
    description: "ν”ΌλΌλ―Έλ”© λ°©ν–¥ (UP: λ¶νƒ€κΈ°-μμµμ‹λ§¤μ, DOWN: λ¬Όνƒ€κΈ°-μ†μ‹¤μ‹λ§¤μ)"
    display_order: 4

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π”Ά μµλ€ νμ (Max Count) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "max_pyramid_count"
    type: "integer"
    default_value: "3"
    required: true
    min_value: "1"
    max_value: "10"
    enum_values: null
    display_name: "μµλ€ νμ"
    description: "μµλ€ ν”ΌλΌλ―Έλ”© νμ (1-10ν, μ†μ§„ μ‹ λΉ„ν™μ„±ν™”)"
    display_order: 5

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # β οΈ νƒ€μ„ν”„λ μ„ (Timeframe) - μ¶”μ λ³€μ λ”°λ¦„ (μ •λ³΄μ©)
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "timeframe"
    type: "enum"
    default_value: "follow_tracked_variable"
    required: false
    min_value: null
    max_value: null
    enum_values:
      - "follow_tracked_variable"    # μ¶”μ  λ³€μμ νƒ€μ„ν”„λ μ„ λ”°λ¦„ (κΈ°λ³Έ)
      - "realtime"                   # μ‹¤μ‹κ°„ (ν„μ¬κ°€μ©)
    display_name: "νƒ€μ„ν”„λ μ„"
    description: "μ¶”μ  λ³€μμ νƒ€μ„ν”„λ μ„μ„ λ”°λ¦„ (λ³„λ„ μ„¤μ • λ¶ν•„μ”)"
    display_order: 6
