# ═══════════════════════════════════════════════════════════════
# 현재가 (CURRENT_PRICE) - 파라미터 파일
# ═══════════════════════════════════════════════════════════════

# 현재가는 기본적으로 파라미터가 필요 없는 변수입니다
# 마켓 데이터에서 직접 가져오는 값이므로 사용자 설정 불필요

parameters: []

# 메타 정보
variable_info:
  parameter_required: false
  data_source: "market_api"
  update_frequency: "realtime"
  precision: 8  # 소수점 8자리까지 지원
