# ═══════════════════════════════════════════════════════════════
# 🎯 META_PYRAMID_TARGET (피라미딩) - 매개변수 정의
# ═══════════════════════════════════════════════════════════════
# 대응 테이블: tv_variable_parameters
# 지표 ID: META_PYRAMID_TARGET
# ═══════════════════════════════════════════════════════════════

# 매개변수 목록
parameters:
  # ─────────────────────────────────────────────────────────────
  # 📊 계산 방식 (Calculation Method) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  calculation_method:
    # 기본 정보
    parameter_name: "calculation_method"
    parameter_type: "enum"
    default_value: "entry_price_percent"
    is_required: true

    # 선택 옵션
    enum_values:
      - "average_price_percent"      # 평단값 퍼센트포인트 (%p) - 평단가 기준
      - "entry_price_percent"        # 진입값 퍼센트포인트 (%p) - 진입가 기준
      - "static_value_offset"        # 정적차이 (원화/수치) - 절대값 차이
      - "percentage_of_tracked"      # 극값 비율퍼센트 (%) - 최고/최저점 대비

    # 표시 정보
    display_name_ko: "계산 방식"
    display_name_en: "Calculation Method"
    description: "피라미딩 계산 방식 (평단가%p/진입가%p/정적차이/극값비율%)"
    display_order: 1

    # UI 매핑 (한국어 표시용)
    display_mapping:
      "average_price_percent": "평단값 퍼센트포인트 (%p)"
      "entry_price_percent": "진입값 퍼센트포인트 (%p)"
      "static_value_offset": "정적차이 (원화/수치)"
      "percentage_of_tracked": "극값 비율퍼센트 (%)"

    # 추가 속성
    validation_rules:
      - "must_be_valid_enum_value"

    recommended_values:
      conservative: ["entry_price_percent"]
      aggressive: ["percentage_of_tracked", "average_price_percent"]

  # ─────────────────────────────────────────────────────────────
  # 💰 계산값 (Value) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  value:
    # 기본 정보
    parameter_name: "value"
    parameter_type: "decimal"
    default_value: "3.0"
    is_required: true

    # 제약 조건
    min_value: "-50.0"
    max_value: "50.0"

    # 표시 정보
    display_name_ko: "계산값"
    display_name_en: "Value"
    description: "계산에 사용될 값 (퍼센트: 3.0=3%, 원화: 1000=1000원)"
    display_order: 2

    # 추가 속성
    validation_rules:
      - "must_be_decimal"
      - "within_range_minus50_to_50"

    recommended_values:
      conservative: [5.0, 7.0, 10.0]
      moderate: [3.0, 5.0, 7.0]
      aggressive: [1.0, 2.0, 3.0]

    context_specific:
      crypto:
        popular: [3.0, 5.0, 7.0]
        scalping: [1.0, 2.0, 3.0]
      stocks:
        popular: [5.0, 7.0, 10.0]
        swing: [3.0, 5.0, 7.0]

  # ─────────────────────────────────────────────────────────────
  # 🎯 추적 방향 (Trail Direction) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  trail_direction:
    # 기본 정보
    parameter_name: "trail_direction"
    parameter_type: "enum"
    default_value: "up"
    is_required: true

    # 선택 옵션
    enum_values:
      - "up"      # 상향 추적 (불타기 - 상승시 추가 매수)
      - "down"    # 하향 추적 (물타기 - 하락시 추가 매수)

    # 표시 정보
    display_name_ko: "추적 방향"
    display_name_en: "Trail Direction"
    description: "피라미딩 방향 (UP: 불타기, DOWN: 물타기)"
    display_order: 3

    # UI 매핑 (한국어 표시용)
    display_mapping:
      "up": "상향 추적 (불타기)"
      "down": "하향 추적 (물타기)"

    # 추가 속성
    validation_rules:
      - "must_be_valid_enum_value"

    recommended_combinations:
      bullish_strategy:
        direction: ["up"]
        description: "상승 전략에는 불타기 권장"
      bearish_strategy:
        direction: ["down"]
        description: "하락 대응에는 물타기 권장"

  # ─────────────────────────────────────────────────────────────
  # 🔢 최대 횟수 (Max Count) - 필수 매개변수 (피라미딩 전용)
  # ─────────────────────────────────────────────────────────────
  max_count:
    # 기본 정보
    parameter_name: "max_count"
    parameter_type: "integer"
    default_value: "3"
    is_required: true

    # 제약 조건
    min_value: "1"
    max_value: "10"

    # 표시 정보
    display_name_ko: "최대 횟수"
    display_name_en: "Max Count"
    description: "최대 피라미딩 횟수 (1-10회, 리스크 관리)"
    display_order: 4

    # 추가 속성
    validation_rules:
      - "must_be_positive_integer"
      - "within_range_1_to_10"

    recommended_values:
      conservative: [2, 3]
      moderate: [3, 4, 5]
      aggressive: [5, 7, 10]

    risk_specific:
      low_risk: [1, 2]
      medium_risk: [3, 4, 5]
      high_risk: [7, 10]

# ─────────────────────────────────────────────────────────────
# 📝 매개변수 조합 규칙
# ─────────────────────────────────────────────────────────────
parameter_validation:
  # 조합 규칙
  combination_rules:
    - name: "value_direction_consistency"
      description: "값과 방향의 일관성 확인"
      rule: "if trail_direction == 'up' then value should be positive for pyramid buying"

    - name: "count_value_balance"
      description: "횟수와 값의 균형 확인"
      rule: "if max_count > 5 then abs(value) >= 3 for sufficient spacing"

  # 경고 조건
  warnings:
    - condition: "max_count > 5 and abs(value) < 2"
      message: "높은 횟수에 작은 값은 과도한 포지션 증가 위험"

    - condition: "abs(value) > 15"
      message: "너무 큰 값은 피라미딩 기회를 제한할 수 있습니다"

    - condition: "max_count == 1"
      message: "1회 설정은 피라미딩 효과가 제한적입니다"

# ─────────────────────────────────────────────────────────────
# 🎨 UI 표시 설정
# ─────────────────────────────────────────────────────────────
ui_settings:
  parameter_layout: "vertical"  # vertical, horizontal, grid

  calculation_method:
    widget_type: "combobox"
    group_separator: true
    groups:
      basic: ["entry_price_percent", "percentage_of_tracked"]
      advanced: ["average_price_percent", "static_value_offset"]

  value:
    widget_type: "spinbox"
    step_size: 0.5
    decimal_places: 1
    quick_buttons: [1.0, 3.0, 5.0, 7.0, 10.0]

  trail_direction:
    widget_type: "radiobutton"
    layout: "horizontal"
    icons:
      up: "📈"
      down: "📉"

  max_count:
    widget_type: "spinbox"
    step_size: 1
    quick_buttons: [2, 3, 4, 5]
