"""
자동 생성된 컴포넌트 데이터 - 실제 코드베이스 스캔 결과
=========================================================

create_component_logger 사용 패턴과 파일 구조를 기반으로
실제 존재하는 컴포넌트들을 자동 스캔하여 생성됨
"""

REAL_COMPONENT_TREE_DATA = {
    "🖥️ Presentation Layer": {
        "🔧 기타": {
            "🔧 App": "upbit_auto_trading.ui.web.app",
            "🔧 Event Driven Log Viewer Widget": "upbit_auto_trading.ui.widgets.logging.event_driven_log_viewer_widget",
            "⚙️ Event Driven Logging Configuration Section": "upbit_auto_trading.ui.widgets.logging.event_driven_logging_configuration_section",
        },
        "📱 Desktop UI": {
            "🔧 Components": "upbit_auto_trading.ui.desktop.common.components",
            "👨‍💼 Style Manager": "upbit_auto_trading.ui.desktop.common.styles.style_manager",
            "🔧 Theme Notifier": "upbit_auto_trading.ui.desktop.common.theme_notifier",
            "🌐 Clickable Api Status": "upbit_auto_trading.ui.desktop.common.widgets.clickable_api_status",
            "🔧 Navigation Bar": "upbit_auto_trading.ui.desktop.common.widgets.navigation_bar",
            "🔧 Placeholder": "upbit_auto_trading.ui.desktop.common.widgets.placeholder",
            "🔧 Status Bar": "upbit_auto_trading.ui.desktop.common.widgets.status_bar",
            "🏠 Main Window": "upbit_auto_trading.ui.desktop.main_window",
        },
        "📱 Desktop Screens": {
            "🔧 Asset Screener Screen": "upbit_auto_trading.ui.desktop.screens.asset_screener.asset_screener_screen",
            "🔧 Backtesting Screen": "upbit_auto_trading.ui.desktop.screens.backtesting.backtesting_screen",
            "🔧 Backtest Setup": "upbit_auto_trading.ui.desktop.screens.backtesting.components.backtest_setup",
            "📈 Candlestick Chart": "upbit_auto_trading.ui.desktop.screens.chart_view.candlestick_chart",
            "📈 Chart View Screen": "upbit_auto_trading.ui.desktop.screens.chart_view.chart_view_screen",
            "📈 Chart Control Panel": "upbit_auto_trading.ui.desktop.screens.chart_view.components.chart_control_panel",
            "📈 Chart Info Panel": "upbit_auto_trading.ui.desktop.screens.chart_view.components.chart_info_panel",
            "📈 Enhanced Candlestick Chart": "upbit_auto_trading.ui.desktop.screens.chart_view.components.enhanced_candlestick_chart",
            "🔧 Indicator Management Panel": "upbit_auto_trading.ui.desktop.screens.chart_view.components.indicator_management_panel",
            "🔧 Indicator Overlay": "upbit_auto_trading.ui.desktop.screens.chart_view.indicator_overlay",
            "🔧 Trade Marker": "upbit_auto_trading.ui.desktop.screens.chart_view.trade_marker",
            "📊 Dashboard Screen": "upbit_auto_trading.ui.desktop.screens.dashboard.dashboard_screen",
            "🔧 Active Positions Widget": "upbit_auto_trading.ui.desktop.screens.dashboard.widgets.active_positions_widget",
            "🔧 Market Overview Widget": "upbit_auto_trading.ui.desktop.screens.dashboard.widgets.market_overview_widget",
            "🔧 Portfolio Summary Widget": "upbit_auto_trading.ui.desktop.screens.dashboard.widgets.portfolio_summary_widget",
            "🔧 Active Strategies Panel": "upbit_auto_trading.ui.desktop.screens.live_trading.components.active_strategies_panel",
            "🔧 Emergency Controls": "upbit_auto_trading.ui.desktop.screens.live_trading.components.emergency_controls",
            "🔧 Manual Order Panel": "upbit_auto_trading.ui.desktop.screens.live_trading.components.manual_order_panel",
            "🔧 Market Data Panel": "upbit_auto_trading.ui.desktop.screens.live_trading.components.market_data_panel",
            "🔧 Trade History Panel": "upbit_auto_trading.ui.desktop.screens.live_trading.components.trade_history_panel",
            "💰 Live Trading Screen": "upbit_auto_trading.ui.desktop.screens.live_trading.live_trading_screen",
            "🔧 Alert History Panel": "upbit_auto_trading.ui.desktop.screens.monitoring_alerts.components.alert_history_panel",
            "⚙️ Alert Settings Panel": "upbit_auto_trading.ui.desktop.screens.monitoring_alerts.components.alert_settings_panel",
            "🔧 Real Time Monitor": "upbit_auto_trading.ui.desktop.screens.monitoring_alerts.components.real_time_monitor",
            "🔧 Monitoring Alerts Screen": "upbit_auto_trading.ui.desktop.screens.monitoring_alerts.monitoring_alerts_screen",
            "🔧 Notification Center": "upbit_auto_trading.ui.desktop.screens.notification_center.notification_center",
            "🔧 Notification Filter": "upbit_auto_trading.ui.desktop.screens.notification_center.notification_filter",
            "🔧 Notification List": "upbit_auto_trading.ui.desktop.screens.notification_center.notification_list",
            "🔧 Portfolio Composition Panel": "upbit_auto_trading.ui.desktop.screens.portfolio_configuration.components.portfolio_composition_panel",
            "🔧 Portfolio List Panel": "upbit_auto_trading.ui.desktop.screens.portfolio_configuration.components.portfolio_list_panel",
            "🔧 Portfolio Performance Panel": "upbit_auto_trading.ui.desktop.screens.portfolio_configuration.components.portfolio_performance_panel",
            "⚙️ Portfolio Configuration Screen": "upbit_auto_trading.ui.desktop.screens.portfolio_configuration.portfolio_configuration_screen",
            "🌐 Api Key Manager Secure Legacy": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.api_key_manager_secure_legacy",
            "⚙️ Api Settings Presenter": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.presenters.api_settings_presenter",
            "⚙️ Api Settings View": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.views.api_settings_view",
            "🌐 Api Connection Widget": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.widgets.api_connection_widget",
            "🌐 Api Credentials Widget": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.widgets.api_credentials_widget",
            "🌐 Api Permissions Widget": "upbit_auto_trading.ui.desktop.screens.settings.api_settings.widgets.api_permissions_widget",
            "⚙️ Database Settings Presenter": "upbit_auto_trading.ui.desktop.screens.settings.presenters.database_settings_presenter",
            "⚙️ Database Settings View": "upbit_auto_trading.ui.desktop.screens.settings.database_settings.views.database_settings_view",
            "🔧 Database Backup Widget": "upbit_auto_trading.ui.desktop.screens.settings.database_settings.widgets.database_backup_widget",
            "🔧 Database Path Selector": "upbit_auto_trading.ui.desktop.screens.settings.database_settings.widgets.database_path_selector",
            "🔧 Database Status Widget": "upbit_auto_trading.ui.desktop.screens.settings.database_settings.widgets.database_status_widget",
            "🔧 Database Task Progress Widget": "upbit_auto_trading.ui.desktop.screens.settings.database_settings.widgets.database_task_progress_widget",
            "🔧 Database Tab Dto": "upbit_auto_trading.ui.desktop.screens.settings.dtos.database_tab_dto",
            "🔧 Profile Metadata": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.dialogs.profile_metadata",
            "🔧 Profile Metadata Dialog": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.dialogs.profile_metadata_dialog",
            "🔧 Environment Profile View": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.environment_profile_view",
            "🔧 Environment Profile Presenter": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.presenters.environment_profile_presenter",
            "🔧 Profile Selector Section": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.widgets.profile_selector_section",
            "🔧 Quick Environment Buttons": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.widgets.quick_environment_buttons",
            "🔧 Yaml Editor Section": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.widgets.yaml_editor_section",
            "🔧 Yaml Syntax Highlighter": "upbit_auto_trading.ui.desktop.screens.settings.environment_profile.widgets.yaml_syntax_highlighter",
            "🔧 Database Tab View Interface": "upbit_auto_trading.ui.desktop.screens.settings.interfaces.database_tab_view_interface",
            "🔧 Logging Management View": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.logging_management_view",
            "⚙️ Logging Config Presenter": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.presenters.logging_config_presenter",
            "🔧 Logging Management Presenter": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.presenters.logging_management_presenter",
            "🔧 Logging Management Presenter Backup": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.presenters.logging_management_presenter_backup",
            "🔧 Batched Log Updater": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.widgets.batched_log_updater",
            "🔧 Console Viewer Widget": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.widgets.console_viewer_widget",
            "🔧 Log Syntax Highlighter": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.widgets.log_syntax_highlighter",
            "🔧 Log Viewer Widget": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.widgets.log_viewer_widget",
            "⚙️ Logging Settings Widget": "upbit_auto_trading.ui.desktop.screens.settings.logging_management.widgets.logging_settings_widget",
            "⚙️ Notification Settings Presenter": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.presenters.notification_settings_presenter",
            "⚙️ Notification Settings View": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.views.notification_settings_view",
            "🔧 Alert Types Widget": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.widgets.alert_types_widget",
            "🔧 Notification Frequency Widget": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.widgets.notification_frequency_widget",
            "🔧 Notification Methods Widget": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.widgets.notification_methods_widget",
            "🔧 Quiet Hours Widget": "upbit_auto_trading.ui.desktop.screens.settings.notification_settings.widgets.quiet_hours_widget",
            "⚙️ Settings Screen": "upbit_auto_trading.ui.desktop.screens.settings.settings_screen",
            "⚙️ Ui Settings Presenter": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.presenters.ui_settings_presenter",
            "⚙️ Ui Settings View": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.views.ui_settings_view",
            "⚙️ Animation Settings Widget": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.widgets.animation_settings_widget",
            "⚙️ Chart Settings Widget": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.widgets.chart_settings_widget",
            "🔧 Theme Selector Widget": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.widgets.theme_selector_widget",
            "⚙️ Window Settings Widget": "upbit_auto_trading.ui.desktop.screens.settings.ui_settings.widgets.window_settings_widget",
            "📈 Chart Visualizer": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.charts.chart_visualizer",
            "🔧 Simulation Control Widget": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.charts.simulation_control_widget",
            "🔧 Simulation Result Widget": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.charts.simulation_result_widget",
            "🔧 Condition Builder": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.condition_builder",
            "🔧 Condition Validator": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.condition_validator",
            "👨‍💼 Data Source Manager": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.data_sources.data_source_manager",
            "🔧 Data Source Selector": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.data_sources.data_source_selector",
            "👨‍💼 Market Data Manager": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.data_sources.market_data_manager",
            "📈 Minichart Variable Service": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.data_sources.minichart_variable_service",
            "🔧 Parameter Widgets": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.parameter_widgets",
            "🔧 Variable Definitions": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.variable_definitions",
            "🚀 Embedded Simulation Engine": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.engines.embedded_simulation_engine",
            "🔧 Real Data Simulation": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.engines.real_data_simulation",
            "🚀 Robust Simulation Engine": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.engines.robust_simulation_engine",
            "🚀 Simulation Engines": "upbit_auto_trading.ui.desktop.screens.strategy_management.shared_simulation.engines.simulation_engines",
            "🔧 Condition Storage": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.condition_storage",
            "🔧 Preview Components": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.preview_components",
            "🔧 Simulation Panel": "upbit_auto_trading.ui.desktop.screens.strategy_management.strategy_maker.components.simulation_panel",
            "🎯 Strategy Storage": "upbit_auto_trading.ui.desktop.screens.strategy_management.strategy_maker.components.strategy_storage",
            "🎯 Strategy Maker": "upbit_auto_trading.ui.desktop.screens.strategy_management.strategy_maker.strategy_maker",
            "🎯 Strategy Management Screen": "upbit_auto_trading.ui.desktop.screens.strategy_management.strategy_management_screen",
            "🔧 Condition Dialog": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.condition_dialog",
            "🔧 Trigger Detail Widget": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.trigger_detail_widget",
            "🔧 Trigger List Widget": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.core.trigger_list_widget",
            "🔧 Compatibility Validator": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.shared.compatibility_validator",
            "🔧 Trigger Calculator": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.shared.trigger_calculator",
            "🔧 Trigger Simulation Service": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.shared.trigger_simulation_service",
            "🔧 Variable Display System": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.components.shared.variable_display_system",
            "🔧 Trigger Builder Screen": "upbit_auto_trading.ui.desktop.screens.strategy_management.trigger_builder.trigger_builder_screen",
        },
    },
    "🏗️ Application Layer": {
        "🔧 기타": {
            "🔧 Cache Invalidation Service": "upbit_auto_trading.application.caching.cache_invalidation_service",
            "🎯 Strategy Commands": "upbit_auto_trading.application.commands.strategy_commands",
            "🔧 Container": "upbit_auto_trading.application.container",
            "⚙️ Database Config Dto": "upbit_auto_trading.application.dto.database_config_dto",
            "🎯 Strategy Dto": "upbit_auto_trading.application.dto.strategy_dto",
            "🔧 Trigger Dto": "upbit_auto_trading.application.dto.trigger_dto",
            "🔧 Backtest Event Handlers": "upbit_auto_trading.application.event_handlers.backtest_event_handlers",
            "🔧 Base Event Handler": "upbit_auto_trading.application.event_handlers.base_event_handler",
            "🔧 Event Handler Registry": "upbit_auto_trading.application.event_handlers.event_handler_registry",
            "🎯 Strategy Event Handlers": "upbit_auto_trading.application.event_handlers.strategy_event_handlers",
            "🔧 Notification Service": "upbit_auto_trading.application.notifications.notification_service",
            "📊 Dashboard Query Dto": "upbit_auto_trading.application.queries.dto.dashboard_query_dto",
            "🎯 Strategy Query Dto": "upbit_auto_trading.application.queries.dto.strategy_query_dto",
            "🔧 Base Query Handler": "upbit_auto_trading.application.queries.handlers.base_query_handler",
            "📊 Dashboard Query Handler": "upbit_auto_trading.application.queries.handlers.dashboard_query_handler",
            "🎯 Strategy Query Handler": "upbit_auto_trading.application.queries.handlers.strategy_query_handler",
            "🔧 Query Container": "upbit_auto_trading.application.queries.query_container",
            "🔧 Query Dispatcher": "upbit_auto_trading.application.queries.query_dispatcher",
            "🔧 Query Service": "upbit_auto_trading.application.queries.query_service",
        },
        "🔄 Services": {
            "🔧 Backtest Application Service": "upbit_auto_trading.application.services.backtest_application_service",
            "🔧 Base Application Service": "upbit_auto_trading.application.services.base_application_service",
            "🔧 Config Profile Service": "upbit_auto_trading.application.services.config_profile_service",
            "🔧 Database Configuration Service": "upbit_auto_trading.application.services.database_configuration_service",
            "🔧 Database Health Service": "upbit_auto_trading.application.services.database_health_service",
            "🔧 Profile Edit Session Service": "upbit_auto_trading.application.services.profile_edit_session_service",
            "🔧 Profile Metadata Service": "upbit_auto_trading.application.services.profile_metadata_service",
            "🔧 Profile Validation Service": "upbit_auto_trading.application.services.profile_validation_service",
            "🎯 Strategy Application Service": "upbit_auto_trading.application.services.strategy_application_service",
            "🔧 Trigger Application Service": "upbit_auto_trading.application.services.trigger_application_service",
        },
        "📋 Use Cases": {
            "🔧 Database Profile Management Use Case": "upbit_auto_trading.application.use_cases.database_configuration.database_profile_management_use_case",
            "🔧 Database Replacement Use Case": "upbit_auto_trading.application.use_cases.database_configuration.database_replacement_use_case",
            "🔧 Database Replacement Use Case Backup": "upbit_auto_trading.application.use_cases.database_configuration.database_replacement_use_case_backup",
            "🔧 Database Validation Use Case": "upbit_auto_trading.application.use_cases.database_configuration.database_validation_use_case",
            "🔧 System Safety Check Use Case": "upbit_auto_trading.application.use_cases.database_configuration.system_safety_check_use_case",
            "🔧 Profile Editor Use Case": "upbit_auto_trading.application.use_cases.profile_editor_use_case",
            "🔧 Profile Metadata Use Case": "upbit_auto_trading.application.use_cases.profile_metadata_use_case",
            "🔧 Temp File Management Use Case": "upbit_auto_trading.application.use_cases.temp_file_management_use_case",
        },
    },
    "🎯 Domain Layer": {
        "🔧 기타": {
            "🔧 Unified Config Service": "upbit_auto_trading.domain.configuration.services.unified_config_service",
            "⚙️ Database Configuration": "upbit_auto_trading.domain.database_configuration.entities.database_configuration",
            "🔧 Backup Record": "upbit_auto_trading.domain.database_configuration.entities.backup_record",
            "🔧 Database Profile": "upbit_auto_trading.domain.database_configuration.entities.database_profile",
            "🗄️ Database Configuration Repository": "upbit_auto_trading.domain.database_configuration.repositories.database_configuration_repository",
            "🗄️ Idatabase Config Repository": "upbit_auto_trading.domain.database_configuration.repositories.idatabase_config_repository",
            "🔧 Database Backup Service": "upbit_auto_trading.domain.database_configuration.services.database_backup_service",
            "🔧 Database Health Monitoring Service": "upbit_auto_trading.domain.database_configuration.services.database_health_monitoring_service",
            "🔧 Database Path Service": "upbit_auto_trading.domain.database_configuration.services.database_path_service",
            "🔧 Database Health Report": "upbit_auto_trading.domain.database_configuration.value_objects.database_health_report",
            "🔧 Database Path": "upbit_auto_trading.domain.database_configuration.value_objects.database_path",
            "🔧 Database Type": "upbit_auto_trading.domain.database_configuration.value_objects.database_type",
            "🔧   Init  ": "upbit_auto_trading.domain.events.__init__",
            "🔧 Backtest Events": "upbit_auto_trading.domain.events.backtest_events",
            "🔧 Base Domain Event": "upbit_auto_trading.domain.events.base_domain_event",
            "🔧 Domain Event Publisher": "upbit_auto_trading.domain.events.domain_event_publisher",
            "🎯 Strategy Events": "upbit_auto_trading.domain.events.strategy_events",
            "🎯 Strategy Events Fixed": "upbit_auto_trading.domain.events.strategy_events_fixed",
            "💰 Trading Events": "upbit_auto_trading.domain.events.trading_events",
            "🔧 Trigger Events": "upbit_auto_trading.domain.events.trigger_events",
            "🔧 Domain Exceptions": "upbit_auto_trading.domain.exceptions.domain_exceptions",
            "🔧 Notification": "upbit_auto_trading.domain.models.notification",
            "🔧 Profile Editor Session": "upbit_auto_trading.domain.profile_management.entities.profile_editor_session",
            "🔧 Profile Metadata": "upbit_auto_trading.domain.profile_management.entities.profile_metadata",
            "🔧 Profile Display Name": "upbit_auto_trading.domain.profile_management.value_objects.profile_display_name",
            "🔧 Yaml Content": "upbit_auto_trading.domain.profile_management.value_objects.yaml_content",
            "🗄️ Backtest Repository": "upbit_auto_trading.domain.repositories.backtest_repository",
            "🗄️ Base Repository": "upbit_auto_trading.domain.repositories.base_repository",
            "🗄️ Market Data Repository": "upbit_auto_trading.domain.repositories.market_data_repository",
            "🗄️ Repository Factory": "upbit_auto_trading.domain.repositories.repository_factory",
            "🗄️ Secure Keys Repository": "upbit_auto_trading.domain.repositories.secure_keys_repository",
            "⚙️ Settings Repository": "upbit_auto_trading.domain.repositories.settings_repository",
            "🎯 Strategy Repository": "upbit_auto_trading.domain.repositories.strategy_repository",
            "🗄️ Trigger Repository": "upbit_auto_trading.domain.repositories.trigger_repository",
            "🔧 Comparison Operator": "upbit_auto_trading.domain.value_objects.comparison_operator",
            "🔧 Compatibility Rules": "upbit_auto_trading.domain.value_objects.compatibility_rules",
            "🔧 Conflict Resolution": "upbit_auto_trading.domain.value_objects.conflict_resolution",
            "🔧 Signal Type": "upbit_auto_trading.domain.value_objects.signal_type",
            "🎯 Strategy Config": "upbit_auto_trading.domain.value_objects.strategy_config",
            "🎯 Strategy Id": "upbit_auto_trading.domain.value_objects.strategy_id",
            "🎯 Strategy Role": "upbit_auto_trading.domain.value_objects.strategy_role",
            "🔧 Trigger Id": "upbit_auto_trading.domain.value_objects.trigger_id",
        },
        "🏪 Entities": {
            "🔧 Management Rule": "upbit_auto_trading.domain.entities.management_rule",
            "🎯 Strategy": "upbit_auto_trading.domain.entities.strategy",
            "🎯 Strategy Factory": "upbit_auto_trading.domain.entities.strategy_factory",
            "🔧 Trigger": "upbit_auto_trading.domain.entities.trigger",
        },
        "🔧 Services": {
            "🔧 Business Logic Adapter": "upbit_auto_trading.domain.services.business_logic_adapter",
            "🔧 Normalization Service": "upbit_auto_trading.domain.services.normalization_service",
            "🎯 Strategy Compatibility Service": "upbit_auto_trading.domain.services.strategy_compatibility_service",
            "🔧 Trigger Evaluation Service": "upbit_auto_trading.domain.services.trigger_evaluation_service",
        },
    },
    "🔌 Infrastructure Layer": {
        "🔧 기타": {
            "🔧 Alerttypeswidget": "AlertTypesWidget",
            "⚙️ Animationsettingswidget": "AnimationSettingsWidget",
            "🌐 Apiconnectionwidget": "ApiConnectionWidget",
            "🌐 Apicredentialswidget": "ApiCredentialsWidget",
            "🌐 Apikeymanagersecure": "ApiKeyManagerSecure",
            "🌐 Apikeyservice": "ApiKeyService",
            "🌐 Apipermissionswidget": "ApiPermissionsWidget",
            "⚙️ Apisettingspresenter": "ApiSettingsPresenter",
            "⚙️ Apisettingsview": "ApiSettingsView",
            "🔧 Applicationcontainer": "ApplicationContainer",
            "🔧 Backuprecord": "BackupRecord",
            "🔧 Cacheinvalidationservice": "CacheInvalidationService",
            "⚙️ Chartsettingswidget": "ChartSettingsWidget",
            "🌐 Clickableapistatus": "ClickableApiStatus",
            "🔧 Conditionstorage": "ConditionStorage",
            "🔧 Configprofileservice": "ConfigProfileService",
            "🔧 Consoleviewerwidget": "ConsoleViewerWidget",
            "👨‍💼 Datasourcemanager": "DataSourceManager",
            "🔧 Databasebackupservice": "DatabaseBackupService",
            "🔧 Databasebackupwidget": "DatabaseBackupWidget",
            "🗄️ Databaseconfigrepository": "DatabaseConfigRepository",
            "⚙️ Databaseconfiguration": "DatabaseConfiguration",
            "🔧 Databaseconfigurationservice": "DatabaseConfigurationAppService",
            "🔧 Databaseconnectionservice": "DatabaseConnectionService",
            "🔧 Databasehealthmonitoring": "DatabaseHealthMonitoring",
            "🔧 Databasehealthservice": "DatabaseHealthService",
            "🔧 Databasepath": "DatabasePath",
            "🔧 Databasepathselector": "DatabasePathSelector",
            "🔧 Databasepathselectorgroup": "DatabasePathSelectorGroup",
            "🔧 Databasepathservice": "DatabasePathService",
            "🔧 Databaseprofile": "DatabaseProfile",
            "🔧 Databaseprofilemanagement": "DatabaseProfileManagement",
            "🔧 Databaseprogresswidget": "DatabaseProgressWidget",
            "🔧 Databasereplacementusecase": "DatabaseReplacementUseCase",
            "⚙️ Databasesettingspresenter": "DatabaseSettingsPresenter",
            "⚙️ Databasesettingsview": "DatabaseSettingsView",
            "🔧 Databasestatuswidget": "DatabaseStatusWidget",
            "🔧 Databasetaskprogresswidget": "DatabaseTaskProgressWidget",
            "🔧 Databasetype": "DatabaseType",
            "🔧 Databasevalidation": "DatabaseValidation",
            "🔧 Domainevent": "DomainEvent",
            "🔧 Domaineventpublisher": "DomainEventPublisher",
            "🔧 Environmentprofilepresenter": "EnvironmentProfilePresenter",
            "🔧 Environmentprofileview": "EnvironmentProfileView",
            "🔧 Eventdrivenlogviewerwidget": "EventDrivenLogViewerWidget",
            "⚙️ Eventdrivenloggingconfigurationsection": "EventDrivenLoggingConfigurationSection",
            "🔧 Eventhandlerregistry": "EventHandlerRegistry",
            "🔧 Filesystemservice": "FileSystemService",
            "🔧 Logsyntaxhighlighter": "LogSyntaxHighlighter",
            "🔧 Logviewerwidget": "LogViewerWidget",
            "🔧 Loggingmanagementpresenter": "LoggingManagementPresenter",
            "🔧 Loggingmanagementview": "LoggingManagementView",
            "⚙️ Loggingsettingswidget": "LoggingSettingsWidget",
            "🔧 Mvpcontainer": "MVPContainer",
            "🔧 Mainwindow": "MainWindow",
            "🔧 Mockthemeservice": "MockThemeService",
            "🔧 Notificationfrequencywidget": "NotificationFrequencyWidget",
            "🔧 Notificationmethodswidget": "NotificationMethodsWidget",
            "⚙️ Notificationsettingspresenter": "NotificationSettingsPresenter",
            "⚙️ Notificationsettingsview": "NotificationSettingsView",
            "🔧 Profileeditsessionservice": "ProfileEditSessionService",
            "🔧 Profileeditorsession": "ProfileEditorSession",
            "🔧 Profileeditorusecase": "ProfileEditorUseCase",
            "🔧 Profilemetadata": "ProfileMetadata",
            "🔧 Profilemetadatadialog": "ProfileMetadataDialog",
            "🗄️ Profilemetadatarepository": "ProfileMetadataRepository",
            "🔧 Profilemetadataservice": "ProfileMetadataService",
            "🔧 Profilemetadatausecase": "ProfileMetadataUseCase",
            "🔧 Profileselectorsection": "ProfileSelectorSection",
            "🔧 Profilevalidationservice": "ProfileValidationService",
            "🔧 Quickenvironmentbuttons": "QuickEnvironmentButtons",
            "🔧 Quiethourswidget": "QuietHoursWidget",
            "🔧 Realdatasimulation": "RealDataSimulation",
            "⚙️ Settingspresenter": "SettingsPresenter",
            "⚙️ Settingsscreen": "SettingsScreen",
            "🔧 Simplefailuremonitor": "SimpleFailureMonitor",
            "🔧 Simulationcontrol": "SimulationControl",
            "🎯 Strategymanagement": "StrategyManagement",
            "🔧 Systemsafetycheckusecase": "SystemSafetyCheckUseCase",
            "🔧 Tempfilemanagementusecase": "TempFileManagementUseCase",
            "👨‍💼 Tempfilemanager": "TempFileManager",
            "🔧 Themeselectorwidget": "ThemeSelectorWidget",
            "🔧 Themeservice": "ThemeService",
            "🔧 Triggerbuilder": "TriggerBuilder",
            "🔧 Triggerdetail": "TriggerDetail",
            "🔧 Triggerlist": "TriggerList",
            "⚙️ Uisettingspresenter": "UISettingsPresenter",
            "⚙️ Uisettingsview": "UISettingsView",
            "🔧 Unifiedconfigservice": "UnifiedConfigService",
            "⚙️ Windowsettingswidget": "WindowSettingsWidget",
            "🔧 Yamlcontent": "YamlContent",
            "🔧 Yamleditorsection": "YamlEditorSection",
            "🔧 Yamlparser": "YamlParser",
            "🔧 Yamlsyntaxhighlighter": "YamlSyntaxHighlighter",
            "🔧 Backtest Analyzer": "upbit_auto_trading.business_logic.backtester.backtest_analyzer",
            "👨‍💼 Backtest Results Manager": "upbit_auto_trading.business_logic.backtester.backtest_results_manager",
            "🔧 Backtest Runner": "upbit_auto_trading.business_logic.backtester.backtest_runner",
            "🔧 Alert Condition": "upbit_auto_trading.business_logic.monitoring.alert_condition",
            "👨‍💼 Alert Manager": "upbit_auto_trading.business_logic.monitoring.alert_manager",
            "🔧 Market Data Provider": "upbit_auto_trading.business_logic.monitoring.market_data_provider",
            "🔧 Market Monitor": "upbit_auto_trading.business_logic.monitoring.market_monitor",
            "🔧 System Monitor": "upbit_auto_trading.business_logic.monitoring.system_monitor",
            "🔧 Trade Data Provider": "upbit_auto_trading.business_logic.monitoring.trade_data_provider",
            "🔧 Trade Monitor": "upbit_auto_trading.business_logic.monitoring.trade_monitor",
            "🔧 Portfolio Backtest": "upbit_auto_trading.business_logic.portfolio.portfolio_backtest",
            "👨‍💼 Portfolio Manager": "upbit_auto_trading.business_logic.portfolio.portfolio_manager",
            "🔧 Portfolio Performance": "upbit_auto_trading.business_logic.portfolio.portfolio_performance",
            "🔧 Base Screener": "upbit_auto_trading.business_logic.screener.base_screener",
            "🔧 Screener Result": "upbit_auto_trading.business_logic.screener.screener_result",
            "🎯 Base Strategy": "upbit_auto_trading.business_logic.strategy.base_strategy",
            "🔧 Basic Strategies": "upbit_auto_trading.business_logic.strategy.basic_strategies",
            "👨‍💼 Db Combination Manager": "upbit_auto_trading.business_logic.strategy.db_combination_manager",
            "🎯 Role Based Strategy": "upbit_auto_trading.business_logic.strategy.role_based_strategy",
            "🎯 Strategy Combination": "upbit_auto_trading.business_logic.strategy.strategy_combination",
            "🎯 Strategy Factory": "upbit_auto_trading.business_logic.strategy.strategy_factory",
            "🎯 Strategy Interface": "upbit_auto_trading.business_logic.strategy.strategy_interface",
            "🎯 Strategy Manager": "upbit_auto_trading.business_logic.strategy.strategy_manager",
            "🎯 Strategy Parameter": "upbit_auto_trading.business_logic.strategy.strategy_parameter",
            "💰 Trading Strategies": "upbit_auto_trading.business_logic.strategy.trading_strategies",
            "👨‍💼 Order Manager": "upbit_auto_trading.business_logic.trader.order_manager",
            "⚙️ Trading Settings": "upbit_auto_trading.business_logic.trader.trading_settings",
            "💰 Trading State": "upbit_auto_trading.business_logic.trader.trading_state",
            "🔧 Simple Paths": "upbit_auto_trading.config.simple_paths",
            "🔧 Utils": "upbit_auto_trading.core.utils",
            "🔧 Data Collector": "upbit_auto_trading.data_layer.collectors.data_collector",
            "🌐 Upbit Api": "upbit_auto_trading.data_layer.collectors.upbit_api",
            "🔧 Upbit Websocket": "upbit_auto_trading.data_layer.collectors.upbit_websocket",
            "👨‍💼 Database Manager": "upbit_auto_trading.data_layer.storage.database_manager",
            "📈 Minichart Variable Models": "upbit_auto_trading.data_layer.minichart_variable_models",
            "🔧 Models": "upbit_auto_trading.data_layer.models",
            "🔧 Data Processor": "upbit_auto_trading.data_layer.processors.data_processor",
            "🔧 Indicator Processor": "upbit_auto_trading.data_layer.processors.indicator_processor",
            "👨‍💼 Backup Manager": "upbit_auto_trading.data_layer.storage.backup_manager",
            "🔧 Market Data Storage": "upbit_auto_trading.data_layer.storage.market_data_storage",
            "🎯 Strategy Models": "upbit_auto_trading.data_layer.strategy_models",
            "⚙️ Settings View Interface": "upbit_auto_trading.presentation.interfaces.settings_view_interface",
            "🔧 View Interfaces": "upbit_auto_trading.presentation.interfaces.view_interfaces",
            "🔧 Mvp Container": "upbit_auto_trading.presentation.mvp_container",
            "⚙️ Settings Presenter": "upbit_auto_trading.presentation.presenters.settings_presenter",
            "🎯 Strategy Maker Presenter": "upbit_auto_trading.presentation.presenters.strategy_maker_presenter",
            "🔧 Trigger Builder Presenter": "upbit_auto_trading.presentation.presenters.trigger_builder_presenter",
            "🎯 Strategy Maker View": "upbit_auto_trading.presentation.views.strategy_maker_view",
        },
        "🌐 External APIs": {
            "⚙️ Config Loader": "upbit_auto_trading.infrastructure.config.loaders.config_loader",
            "⚙️ Config Models": "upbit_auto_trading.infrastructure.config.models.config_models",
            "🔧 Paths": "upbit_auto_trading.infrastructure.configuration.paths",
            "👨‍💼 Database Manager": "upbit_auto_trading.infrastructure.database.database_manager",
            "🔧 App Context": "upbit_auto_trading.infrastructure.dependency_injection.app_context",
            "🔧 Container": "upbit_auto_trading.infrastructure.dependency_injection.container",
            "🔧 Event Bus Interface": "upbit_auto_trading.infrastructure.events.bus.event_bus_interface",
            "🔧 In Memory Event Bus": "upbit_auto_trading.infrastructure.events.bus.in_memory_event_bus",
            "🔧 Domain Event Publisher Impl": "upbit_auto_trading.infrastructure.events.domain_event_publisher_impl",
            "🔧 Event Bus Factory": "upbit_auto_trading.infrastructure.events.event_bus_factory",
            "🔧 Event System Initializer": "upbit_auto_trading.infrastructure.events.event_system_initializer",
            "🔧 Logging Events": "upbit_auto_trading.infrastructure.events.logging_events",
            "🔧 Sqlite Event Storage": "upbit_auto_trading.infrastructure.events.storage.sqlite_event_storage",
            "🌐 Api Client Factory": "upbit_auto_trading.infrastructure.external_apis.api_client_factory",
            "🌐 Api Client Base": "upbit_auto_trading.infrastructure.external_apis.common.api_client_base",
            "🔧 Upbit Auth": "upbit_auto_trading.infrastructure.external_apis.upbit.upbit_auth",
            "🔧 Upbit Client": "upbit_auto_trading.infrastructure.external_apis.upbit.upbit_client",
            "🔧 Upbit Private Client": "upbit_auto_trading.infrastructure.external_apis.upbit.upbit_private_client",
            "🔧 Upbit Public Client": "upbit_auto_trading.infrastructure.external_apis.upbit.upbit_public_client",
            "🎯 Strategy Mapper": "upbit_auto_trading.infrastructure.mappers.strategy_mapper",
            "🔧 Simple Failure Monitor": "upbit_auto_trading.infrastructure.monitoring.simple_failure_monitor",
            "🗄️ Database Configuration Repository Impl": "upbit_auto_trading.infrastructure.persistence.database_configuration_repository_impl",
            "🗄️ Profile Metadata Repository": "upbit_auto_trading.infrastructure.profile_storage.profile_metadata_repository",
            "👨‍💼 Temp File Manager": "upbit_auto_trading.infrastructure.profile_storage.temp_file_manager",
            "🌐 Api Key Service": "upbit_auto_trading.infrastructure.services.api_key_service",
            "🔧 Database Connection Service": "upbit_auto_trading.infrastructure.services.database_connection_service",
            "🔧 File System Service": "upbit_auto_trading.infrastructure.services.file_system_service",
            "⚙️ Settings Service": "upbit_auto_trading.infrastructure.services.settings_service",
            "🔧 Theme Service": "upbit_auto_trading.infrastructure.services.theme_service",
            "🔧 Yaml Parser": "upbit_auto_trading.infrastructure.yaml_processing.yaml_parser",
        },
        "📝 Logging": {
            "🔧 Briefing Service": "upbit_auto_trading.infrastructure.logging.briefing.briefing_service",
            "🔧 Issue Analyzer": "upbit_auto_trading.infrastructure.logging.briefing.issue_analyzer",
            "🔧 Status Tracker": "upbit_auto_trading.infrastructure.logging.briefing.status_tracker",
            "👨‍💼 Logging Config Manager": "upbit_auto_trading.infrastructure.logging.config.logging_config_manager",
            "⚙️ Enhanced Config": "upbit_auto_trading.infrastructure.logging.configuration.enhanced_config",
            "⚙️ Logging Config": "upbit_auto_trading.infrastructure.logging.configuration.logging_config",
            "📊 Dashboard Service": "upbit_auto_trading.infrastructure.logging.dashboard.dashboard_service",
            "🔧 Issue Detector": "upbit_auto_trading.infrastructure.logging.dashboard.issue_detector",
            "📊 Realtime Dashboard": "upbit_auto_trading.infrastructure.logging.dashboard.realtime_dashboard",
            "🔧 Console Output Capture": "upbit_auto_trading.infrastructure.logging.integration.console_output_capture",
            "👨‍💼 Environment Variable Manager": "upbit_auto_trading.infrastructure.logging.integration.environment_variable_manager",
            "🔧 Log Capture": "upbit_auto_trading.infrastructure.logging.integration.log_capture",
            "👨‍💼 Logging Manager": "upbit_auto_trading.infrastructure.logging.integration.logging_manager",
            "🔧 Logging Interface": "upbit_auto_trading.infrastructure.logging.interfaces.logging_interface",
            "🔧 Async Processor": "upbit_auto_trading.infrastructure.logging.performance.async_processor",
            "👨‍💼 Cache Manager": "upbit_auto_trading.infrastructure.logging.performance.cache_manager",
            "🔧 Memory Optimizer": "upbit_auto_trading.infrastructure.logging.performance.memory_optimizer",
            "🔧 Performance Monitor": "upbit_auto_trading.infrastructure.logging.performance.performance_monitor",
            "🔧 Logging Service": "upbit_auto_trading.infrastructure.logging.services.logging_service",
            "🔧 Log Synchronizer": "upbit_auto_trading.infrastructure.logging.terminal.log_synchronizer",
            "🔧 Output Parser": "upbit_auto_trading.infrastructure.logging.terminal.output_parser",
            "🔧 Terminal Capturer": "upbit_auto_trading.infrastructure.logging.terminal.terminal_capturer",
        },
        "🗄️ Repositories": {
            "🗄️ Database Config Repository": "upbit_auto_trading.infrastructure.repositories.database_config_repository",
            "🗄️ Repository Container": "upbit_auto_trading.infrastructure.repositories.repository_container",
            "🗄️ Sqlite Secure Keys Repository": "upbit_auto_trading.infrastructure.repositories.sqlite_secure_keys_repository",
            "⚙️ Sqlite Settings Repository": "upbit_auto_trading.infrastructure.repositories.sqlite_settings_repository",
            "🎯 Sqlite Strategy Repository": "upbit_auto_trading.infrastructure.repositories.sqlite_strategy_repository",
            "🗄️ Sqlite Trigger Repository": "upbit_auto_trading.infrastructure.repositories.sqlite_trigger_repository",
        },
    },
}

def get_real_components_flat():
    """실제 컴포넌트를 평면 리스트로 변환"""
    flat_list = []

    def _flatten(data, prefix=""):
        for key, value in data.items():
            if isinstance(value, dict):
                if any(isinstance(v, str) for v in value.values()):
                    # 말단 카테고리
                    for item_key, item_value in value.items():
                        if isinstance(item_value, str):
                            display_name = f"{prefix}{item_key}"
                            flat_list.append((display_name, item_value))
                else:
                    # 중간 카테고리
                    current_prefix = f"{prefix}{key} > "
                    _flatten(value, current_prefix)
            else:
                # 개별 컴포넌트
                display_name = f"{prefix}{key}"
                flat_list.append((display_name, value))

    _flatten(REAL_COMPONENT_TREE_DATA)
    return flat_list

def search_real_components(query):
    """실제 컴포넌트 검색"""
    query = query.lower()
    flat_list = get_real_components_flat()

    results = []
    for display_name, path in flat_list:
        if query in display_name.lower() or query in path.lower():
            results.append((display_name, path))

    return results
