database_paths:
  market_data:
    path: D:\projects\upbit-autotrader-vscode\data\market_data.sqlite3
    updated_at: '2025-08-09T19:19:29.918847'
    updated_by: DDD_DatabasePathService
  settings:
    path: D:\projects\upbit-autotrader-vscode\data\settings.sqlite3
    updated_at: '2025-08-09T20:18:50.909878'
    updated_by: DDD_DatabasePathService
  strategies:
    path: D:\projects\upbit-autotrader-vscode\data\strategies.sqlite3
    updated_at: '2025-08-09T19:18:53.624903'
    updated_by: DDD_DatabasePathService
databases:
  market_data:
    last_modified: '2025-08-09T19:19:29.906664'
    path: D:\projects\upbit-autotrader-vscode\data\market_data.sqlite3
    source: null
  settings:
    last_modified: '2025-08-09T20:18:50.897387'
    path: D:\projects\upbit-autotrader-vscode\data\settings.sqlite3
    source: null
  strategies:
    last_modified: '2025-08-09T19:18:53.610938'
    path: D:\projects\upbit-autotrader-vscode\data\strategies.sqlite3
    source: null
user_defined:
  active: true
  market_data_db: data/market_data.sqlite3
  settings_db: data/settings.sqlite3
  strategies_db: data/strategies.sqlite3
