database_paths:
  market_data:
    path: D:\projects\upbit-autotrader-vscode\data\market_data.sqlite3
    updated_at: '2025-08-08T19:40:11.274479'
    updated_by: DDD_DatabasePathService
  settings:
    path: D:\projects\upbit-autotrader-vscode\data\settings.sqlite3
    updated_at: '2025-08-08T20:38:27.968383'
    updated_by: DDD_DatabasePathService
  strategies:
    path: D:\projects\upbit-autotrader-vscode\data\strategies.sqlite3
    updated_at: '2025-08-08T19:39:56.981866'
    updated_by: DDD_DatabasePathService
databases:
  market_data:
    last_modified: '2025-08-08T19:40:11.284465'
    path: D:\projects\upbit-autotrader-vscode\data\market_data.sqlite3
    source: D:\projects\upbit-autotrader-vscode\data\market_data.sqlite3
  settings:
    last_modified: '2025-08-08T20:38:27.979819'
    path: D:\projects\upbit-autotrader-vscode\data\settings.sqlite3
    source: D:\projects\upbit-autotrader-vscode\data\settings.sqlite3
  strategies:
    last_modified: '2025-08-08T19:39:56.994046'
    path: D:\projects\upbit-autotrader-vscode\data\strategies.sqlite3
    source: D:\projects\upbit-autotrader-vscode\data\strategies.sqlite3
user_defined:
  active: true
  market_data_db: data/market_data.sqlite3
  settings_db: data/settings.sqlite3
  strategies_db: data/strategies.sqlite3
