logging:
  level: DEBUG
  console_output: 'true'
  scope: debug_all
  component_focus: ''
  context: debug
  file_logging:
    enabled: true
    path: logs
    level: DEBUG
    max_size_mb: 10
    backup_count: 5
  advanced:
    performance_monitoring: false
runtime:
  watch_config_file: true
  notify_on_change: true
  last_modified: '2025-08-13T19:59:43.242468'
