logging:
  level: DEBUG
  console_output: 'true'
  scope: debug_all
  component_focus: SettingsScreen
  context: debug
  file_logging:
    enabled: true
    path: logs
    level: DEBUG
    max_size_mb: 10
    backup_count: 5
  advanced:
    performance_monitoring: true
runtime:
  watch_config_file: true
  notify_on_change: true
  last_modified: '2025-08-12T21:16:41.270603'
