logging:
  level: INFO
  console_output: false
  scope: normal
  component_focus: ''
  context: development
  file_logging:
    enabled: true
    path: logs
    level: DEBUG
    max_size_mb: 10
    backup_count: 5
  advanced:
    performance_monitoring: false
runtime:
  watch_config_file: true
  notify_on_change: true
  last_modified: '2025-08-12T22:39:56.495392'
