# ================================================================
# 업비트 자동매매 WebSocket v6 설정
# ================================================================
# Simple Mode: 네트워크 사용량 최적화를 위한 압축 포맷 지원
# 환경별 설정: development, testing, production
#
# 설정 우선순위:
# 1. 환경변수 (UPBIT_WEBSOCKET_*)
# 2. 이 YAML 파일
# 3. 코드 기본값
# ================================================================

# 실행 환경 설정
environment: development  # development, testing, staging, production

# 연결 설정
connection:
  public_url: "wss://api.upbit.com/websocket/v1"
  private_url: "wss://api.upbit.com/websocket/v1/private"
  connect_timeout: 10.0  # 연결 타임아웃 (초)
  heartbeat_interval: 30.0  # 하트비트 간격 (초)
  enable_compression: true  # 업비트 압축 기능
  max_message_size: 1048576  # 최대 메시지 크기 (1MB)
  compression_threshold: 1024  # 압축 임계값 (바이트)

# 재연결 설정
reconnection:
  max_attempts: 5  # 최대 재연결 시도 횟수
  base_delay: 1.0  # 기본 지연 시간 (초)
  max_delay: 60.0  # 최대 지연 시간 (초)
  exponential_base: 2.0  # 지수 백오프 계수
  jitter: true  # 지연 시간 랜덤화

# 인증 설정
auth:
  jwt_refresh_threshold: 300.0  # JWT 갱신 임계값 (초, 5분)
  max_auth_retries: 3  # 최대 인증 재시도 횟수
  auth_timeout: 5.0  # 인증 타임아웃 (초)

# 모니터링 설정
monitoring:
  enable_health_check: true  # 헬스체크 활성화
  health_check_interval: 30.0  # 헬스체크 간격 (초)
  enable_performance_metrics: true  # 성능 메트릭 수집
  metrics_update_interval: 10.0  # 메트릭 업데이트 간격 (초)
  enable_connection_metrics: true  # 연결 메트릭 수집
  cleanup_interval: 60.0  # 메트릭 정리 간격 (초)

# Rate Limiter 설정 (업비트 API 제한 준수)
rate_limiter:
  enable_rate_limiter: true  # Rate Limiter 활성화
  enable_dynamic_adjustment: true  # 동적 조정 활성화
  strategy: "balanced"  # conservative, balanced, aggressive
  error_threshold: 2  # 에러 임계값
  reduction_ratio: 0.7  # 감소 비율 (70%)
  recovery_delay: 120.0  # 복구 지연 시간 (초)
  recovery_step: 0.15  # 복구 단계 (15%)
  recovery_interval: 20.0  # 복구 간격 (초)

# ================================================================
# Simple Format 설정 (네트워크 최적화 핵심)
# ================================================================
# Simple Mode는 업비트 압축 포맷을 사용하여 네트워크 사용량을
# 대폭 줄이는 기능입니다. 특히 대용량 데이터를 처리할 때 효과적입니다.
simple_format:
  # Simple Mode 활성화 (기본값: false)
  # true 설정 시 모든 구독 요청에 {"format": "SIMPLE"} 추가
  enable_simple_mode: true

  # 수신 데이터 자동 변환 (권장: true)
  # SIMPLE 포맷으로 수신된 데이터를 자동으로 DEFAULT 포맷으로 변환
  auto_convert_incoming: true

  # SIMPLE 포맷 강제 적용 (고급 옵션)
  # 모든 WebSocket 요청에 format=SIMPLE 강제 적용
  # 주의: enable_simple_mode=true일 때만 유효
  force_simple_format: false

  # SIMPLE 모드에서 압축 사용 (권장: true)
  # SIMPLE 포맷과 함께 WebSocket 압축도 함께 사용
  enable_compression_with_simple: true

  # 포맷 변환 디버깅 (개발용)
  # SIMPLE ↔ DEFAULT 변환 과정의 상세 로그 출력
  debug_format_conversion: false

# ================================================================
# 환경별 설정 예시
# ================================================================

# Development 환경 설정 (빠른 피드백)
development:
  connection:
    connect_timeout: 5.0
    heartbeat_interval: 20.0
  reconnection:
    max_attempts: 3
    base_delay: 0.5
  monitoring:
    health_check_interval: 15.0
    metrics_update_interval: 5.0
  simple_format:
    enable_simple_mode: true  # Simple Mode 테스트를 위해 활성화
    debug_format_conversion: true

# Testing 환경 설정 (빠른 테스트)
testing:
  connection:
    connect_timeout: 3.0
    heartbeat_interval: 10.0
  reconnection:
    max_attempts: 1
    base_delay: 0.1
  monitoring:
    health_check_interval: 5.0
    metrics_update_interval: 1.0
  simple_format:
    enable_simple_mode: true  # 테스트에서 SIMPLE 모드 검증
    debug_format_conversion: true

# Production 환경 설정 (안정성 우선)
production:
  connection:
    connect_timeout: 15.0
    heartbeat_interval: 60.0
  reconnection:
    max_attempts: 10
    base_delay: 2.0
    max_delay: 300.0
  monitoring:
    health_check_interval: 60.0
    metrics_update_interval: 30.0
  simple_format:
    enable_simple_mode: true  # 프로덕션에서 네트워크 최적화
    force_simple_format: true  # 최대 압축 효과
    debug_format_conversion: false

# ================================================================
# 환경변수 오버라이드 참조
# ================================================================
# 다음 환경변수로 설정을 오버라이드할 수 있습니다:
#
# 기본 설정:
# - UPBIT_ENVIRONMENT: 실행 환경
# - UPBIT_WEBSOCKET_PUBLIC_URL: Public WebSocket URL
# - UPBIT_WEBSOCKET_PRIVATE_URL: Private WebSocket URL
# - UPBIT_WEBSOCKET_TIMEOUT: 연결 타임아웃
# - UPBIT_WEBSOCKET_COMPRESSION: 압축 활성화 (true/false)
#
# Rate Limiter:
# - UPBIT_WEBSOCKET_RATE_LIMITER: Rate Limiter 활성화 (true/false)
# - UPBIT_WEBSOCKET_DYNAMIC_RATE_LIMITER: 동적 조정 (true/false)
# - UPBIT_WEBSOCKET_RATE_STRATEGY: 전략 (conservative/balanced/aggressive)
# - UPBIT_WEBSOCKET_ERROR_THRESHOLD: 에러 임계값
#
# Simple Format (신규):
# - UPBIT_WEBSOCKET_SIMPLE_MODE: Simple Mode 활성화 (true/false)
# - UPBIT_WEBSOCKET_AUTO_CONVERT_INCOMING: 자동 변환 (true/false)
# - UPBIT_WEBSOCKET_FORCE_SIMPLE_FORMAT: 강제 SIMPLE (true/false)
# - UPBIT_WEBSOCKET_COMPRESSION_WITH_SIMPLE: SIMPLE+압축 (true/false)
# - UPBIT_WEBSOCKET_DEBUG_FORMAT_CONVERSION: 변환 디버깅 (true/false)
#
# 예시:
# $env:UPBIT_WEBSOCKET_SIMPLE_MODE = "true"
# $env:UPBIT_WEBSOCKET_FORCE_SIMPLE_FORMAT = "true"
# ================================================================
