# ═══════════════════════════════════════════════════════════════
# 🎯 META_TRAILING_STOP (트레일링 스탑) - 매개변수 정의
# ═══════════════════════════════════════════════════════════════
# 대응 테이블: tv_variable_parameters
# 지표 ID: META_TRAILING_STOP
# ═══════════════════════════════════════════════════════════════

# 매개변수 목록
parameters:
  # ─────────────────────────────────────────────────────────────
  # 📊 추적 기간 (Tracking Period) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  tracking_period:
    # 기본 정보
    parameter_name: "tracking_period"
    parameter_type: "integer"
    default_value: "14"
    is_required: true

    # 제약 조건
    min_value: "1"
    max_value: "100"

    # 표시 정보
    display_name_ko: "추적 기간"
    display_name_en: "Tracking Period"
    description: "트레일링 스탑이 추적할 기간 (단기: 5-14 / 중기: 20-50 / 장기: 60-100)"
    display_order: 1

    # 추가 속성
    validation_rules:
      - "must_be_positive_integer"
      - "within_range_1_to_100"

    recommended_values:
      short_term: [5, 10, 14]
      medium_term: [20, 30, 50]
      long_term: [60, 80, 100]

  # ─────────────────────────────────────────────────────────────
  # 📈 임계값 비율 (Threshold Ratio) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  threshold_ratio:
    # 기본 정보
    parameter_name: "threshold_ratio"
    parameter_type: "decimal"
    default_value: "0.02"
    is_required: true

    # 제약 조건
    min_value: "0.001"
    max_value: "0.20"

    # 표시 정보
    display_name_ko: "임계값 비율"
    display_name_en: "Threshold Ratio"
    description: "트레일링 스탑 발동 기준 (0.01=1%, 0.02=2%, 0.05=5%)"
    display_order: 2

    # 권장값
    recommended_values:
      conservative: [0.01, 0.015, 0.02]
      moderate: [0.025, 0.03, 0.04]
      aggressive: [0.05, 0.075, 0.10]

  # ─────────────────────────────────────────────────────────────
  # ⏰ 타임프레임 (Timeframe) - 필수 매개변수
  # ─────────────────────────────────────────────────────────────
  timeframe:
    # 기본 정보
    parameter_name: "timeframe"
    parameter_type: "enum"
    default_value: "position_follow"
    is_required: true

    # 선택 옵션
    enum_values:
      - "position_follow"
      - "1m"
      - "5m"
      - "15m"
      - "1h"
      - "4h"
      - "1d"

    # 표시 정보
    display_name_ko: "타임프레임"
    display_name_en: "Timeframe"
    description: "트레일링 스탑 계산 기준 시간"
    display_order: 3

    # UI 매핑
    display_mapping:
      "position_follow": "포지션 설정 따름"
      "1m": "1분"
      "5m": "5분"
      "15m": "15분"
      "1h": "1시간"
      "4h": "4시간"
      "1d": "1일"
