parameters:
  period:
    type: integer
    default: '14'
    required: true
    description: '단기: 5,10,20 / 중기: 60,120 / 장기: 200,240'
    min: '1'
    max: '240'
  timeframe:
    type: enum
    default: position_follow
    required: true
    description: 봉 단위 시간
    allowed:
    - position_follow
    - 1m
    - 3m
    - 5m
    - 10m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    - 1w
    - 1M
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
