parameters:
  calculation_method:
    type: enum
    default: entry_price_percent
    required: true
    description: 피라미딩 계산 방식 (평단가%p/진입가%p/정적차이/극값비율%)
    allowed:
    - average_price_percent
    - entry_price_percent
    - static_value_offset
    - percentage_of_tracked
  max_count:
    type: integer
    default: '3'
    required: true
    description: 최대 피라미딩 횟수 (1-10회, 리스크 관리)
    min: '1'
    max: '10'
  trail_direction:
    type: enum
    default: up
    required: true
    description: '피라미딩 방향 (UP: 불타기, DOWN: 물타기)'
    allowed:
    - up
    - down
  value:
    type: decimal
    default: '3.0'
    required: true
    description: '계산에 사용될 값 (퍼센트: 3.0=3%, 원화: 1000=1000원)'
    min: '-50.0'
    max: '50.0'
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
