# 업비트 자동매매 시스템 설정 파일

# API 설정
api:
  upbit:
    base_url: "https://api.upbit.com/v1"
    websocket_url: "wss://api.upbit.com/websocket/v1"
    # API 키는 환경 변수 또는 .env 파일에서 로드됩니다.
    # UPBIT_ACCESS_KEY, UPBIT_SECRET_KEY

# 데이터베이스 설정
database:
  type: "sqlite"  # sqlite, mysql, postgresql
  path: "data/upbit_auto_trading.db"  # SQLite 데이터베이스 파일 경로
  # MySQL/PostgreSQL 설정 (필요시 주석 해제)
  # host: "localhost"
  # port: 3306
  # username: "user"
  # password: "password"
  # database_name: "upbit_auto_trading"
  
  # 데이터 관리 정책
  data_retention:
    minute_candles_days: 90  # 분봉 데이터 보관 기간 (일)
    daily_candles_days: 365  # 일봉 데이터 보관 기간 (일)
    max_database_size_gb: 10  # 최대 데이터베이스 크기 (GB)

# 거래 설정
trading:
  default_fee: 0.0005  # 기본 거래 수수료 (0.05%)
  default_slippage: 0.001  # 기본 슬리피지 (0.1%)
  max_position_size: 0.3  # 최대 포지션 크기 (전체 자본 대비 %)
  default_risk_percent: 0.02  # 기본 위험 비율 (2%)

# 백테스팅 설정
backtesting:
  default_initial_capital: 10000000  # 기본 초기 자본 (1천만원)
  default_timeframe: "1h"  # 기본 시간대 (1시간)
  default_period: 90  # 기본 백테스팅 기간 (일)

# 스크리닝 설정
screening:
  default_volume_threshold: 1000000000  # 기본 거래량 임계값 (10억원)
  default_volatility_min: 0.05  # 기본 최소 변동성 (5%)
  default_volatility_max: 0.20  # 기본 최대 변동성 (20%)

# 알림 설정
notifications:
  enabled: true
  # 알림 유형 설정
  types:
    trade_executed: true  # 거래 체결 알림
    price_alert: true  # 가격 알림
    system_error: true  # 시스템 오류 알림
  # 알림 방법 설정
  methods:
    desktop: true  # 데스크톱 알림
    email: false  # 이메일 알림
    # 이메일 설정 (필요시 주석 해제)
    # email_settings:
    #   smtp_server: "smtp.gmail.com"
    #   smtp_port: 587
    #   sender_email: "your-email@gmail.com"
    #   sender_password: ""  # 앱 비밀번호 사용 권장

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/upbit_auto_trading.log"
  max_size_mb: 10
  backup_count: 5

# UI 설정
ui:
  theme: "light"  # light, dark
  chart_update_interval_sec: 5  # 차트 업데이트 간격 (초)
  save_window_state: true  # 창 상태 저장 여부