"database":
  "base_directory": "upbit_auto_trading/data"
  "databases":
    "market_data": "market_data.sqlite3"
    "settings": "settings.sqlite3"
    "strategies": "strategies.sqlite3"
  "environments":
    "development":
      "base_directory": "data"
    "portable":
      "base_directory": "${PORTABLE_DIR}/data"
    "production":
      "base_directory": "upbit_auto_trading/data"
  "table_mappings":
    "backtest_results": "market_data"
    "chart_variables": "settings"
    "component_strategy": "settings"
    "market_data": "market_data"
    "migration_info": "strategies"
    "ohlcv_data": "market_data"
    "portfolios": "market_data"
    "strategies": "settings"
    "strategy_execution": "strategies"
    "trading_conditions": "settings"
    "tv_comparison_groups": "settings"
    "tv_schema_version": "settings"
    "tv_trading_variables": "settings"
"runtime":
  "active_environment": "production"
  "auto_create_databases": !!bool "true"
  "enable_connection_pooling": !!bool "true"
"user_defined":
  "active": !!bool "true"
  "market_data_db": "upbit_auto_trading/data/market_data.sqlite3"
  "settings_db": "upbit_auto_trading/data/settings.sqlite3"
  "strategies_db": "upbit_auto_trading/data/strategies.sqlite3"
