# 업비트 WebSocket v6.0 설정 파일
# ================================================
# DDD + MVP + Infrastructure v4.0 호환 설정
# 사용자 투명 포맷 변환과 압축 최적화 지원

# 연결 설정
connection:
  # WebSocket 엔드포인트 (업비트 공식)
  # 업비트는 Public/Private 다른 엔드포인트 사용 (2025년 현재)
  public_url: "wss://api.upbit.com/websocket/v1"
  private_url: "wss://api.upbit.com/websocket/v1/private"

  # 하위 호환성을 위한 기본 URL (Public 기준)
  url: "wss://api.upbit.com/websocket/v1"

  connection_timeout: 10.0
  ping_interval: 20.0
  ping_timeout: 10.0
  close_timeout: 10.0
  heartbeat_interval: 30.0
  heartbeat_timeout: 60.0
  max_message_size: 1048576  # 1MB (1024 * 1024)

# 재연결 설정
reconnection:
  enabled: true
  max_attempts: 5
  base_delay: 2.0
  max_delay: 60.0
  backoff_multiplier: 2.0

# 백프레셔 설정 (NEW)
backpressure:
  strategy: "drop_oldest"  # "drop_oldest", "drop_newest", "throttle", "coalesce"
  max_queue_size: 1000
  warning_threshold: 0.8  # 80%
  coalesce_window_ms: 100
  throttle_interval_ms: 50

# 구독 설정
subscription:
  max_subscriptions: 10
  batch_size: 5
  timeout: 30.0
  format_preference: "auto"  # "auto", "simple", "default"
  public_pool_size: 3
  private_pool_size: 2
  max_symbols_per_request: 100  # 업비트 제한
  auto_cleanup_interval: 300.0  # 5분마다 자동 정리 (NEW)
  grace_period: 30.0  # 구독 해제 후 대기 시간 (NEW)

# 포맷 관리 (사용자 투명 변환)
format:
  # 내부 시스템은 항상 DEFAULT 포맷으로 동작
  internal_format: "default"

  # 네트워크 전송 시 SIMPLE 포맷 사용 (대역폭 최적화)
  transmission_format: "simple"

  # 사용자 API는 투명하게 DEFAULT 포맷 제공
  user_interface_format: "default"

  # 자동 변환 활성화
  enable_transparent_conversion: true

  # 포맷 변환 로깅 (디버깅용)
  log_format_conversion: false

# 성능 설정
performance:
  message_buffer_size: 1000
  max_memory_mb: 100.0

  # 압축 설정 (네트워크 최적화)
  enable_compression: true
  compression_level: 6  # 1(빠름) ~ 9(최대압축)

  # SIMPLE 포맷 활성화 (대역폭 절약)
  enable_simple_format: true

# 로깅 설정
logging:
  level: "INFO"
  enable_debug: false
  log_messages: false
  log_performance_metrics: true
  log_format_conversion: false

# 모니터링 설정 (NEW)
monitoring:
  metrics_collection_interval: 10.0
  health_check_interval: 30.0
  performance_window_size: 100
  # 알림 임계값들
  alert_error_rate_threshold: 0.05  # 5% 에러율
  alert_latency_threshold_ms: 1000.0  # 1초 지연
  alert_queue_threshold: 0.8  # 큐 80% 사용률
  alert_reconnect_threshold: 3  # 3회 이상 재연결

# 인증 설정 (NEW)
auth:
  jwt_refresh_threshold: 0.8  # 80% 만료 시점에 갱신
  jwt_refresh_retry_count: 3
  jwt_refresh_timeout: 10.0
  fallback_to_rest: true  # JWT 실패 시 REST API 폴백

# 비동기 작업 타이밍 (NEW)
async_timing:
  health_check_sleep: 30  # 헬스체크 주기 (초)
  metrics_collection_sleep: 300  # 메트릭 수집 주기 (초, 5분)
  jwt_refresh_sleep: 30  # JWT 갱신 체크 주기 (초)
  jwt_error_sleep: 60  # JWT 오류 시 대기 (초)
  error_prevention_sleep: 0.1  # 연속 오류 방지 (초)
  queue_timeout: 1.0  # 큐 대기 최대 시간 (초)

# 개발 환경 설정
development:
  # Dry-run 모드 (기본값)
  enable_dry_run: true

  # 디버깅 지원
  enable_detailed_logging: false
  enable_message_dump: false

  # 성능 모니터링
  enable_performance_tracking: true
