parameters:
  exponential_factor:
    type: decimal
    default: '2.0'
    required: false
    description: 지수 가중치 (2/(기간+1)이 표준)
    min: '0.1'
    max: '10.0'
  period:
    type: integer
    default: '12'
    required: true
    description: 지수이동평균 계산 기간
    min: '1'
    max: '240'
  timeframe:
    type: enum
    default: position_follow
    required: true
    description: 봉 단위 시간
    allowed:
    - position_follow
    - 1m
    - 3m
    - 5m
    - 10m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    - 1w
    - 1M
parameter_validation:
  validation_rules: 파라미터 검증 규칙
  error_messages: 오류 메시지 정의
ui_settings:
  input_type: form
  layout: vertical
  grouping: by_category
