# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
# π― META_TRAILING_STOP (νΈλ μΌλ§ μ¤νƒ‘) - λ§¤κ°λ³€μ μ •μ
# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
# λ€μ‘ ν…μ΄λΈ”: tv_variable_parameters
# μ§€ν‘ ID: META_TRAILING_STOP
# β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•

# λ§¤κ°λ³€μ λ©λ΅
parameters:
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ κ³„μ‚° λ°©μ‹ (Calculation Method) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  calculation_method:
    # κΈ°λ³Έ μ •λ³΄
    parameter_name: "calculation_method"
    parameter_type: "enum"
    default_value: "percentage_of_tracked"
    is_required: true

    # μ„ νƒ μµμ…
    enum_values:
      - "average_price_percent"      # ν‰λ‹¨κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p)
      - "entry_price_percent"        # μ§„μ…κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p)
      - "static_value_offset"        # μ •μ μ°¨μ΄ (μ›ν™”/μμΉ)
      - "percentage_of_tracked"      # κ·Ήκ°’ λΉ„μ¨νΌμ„ΌνΈ (%)

    # ν‘μ‹ μ •λ³΄
    display_name_ko: "κ³„μ‚° λ°©μ‹"
    display_name_en: "Calculation Method"
    description: "νΈλ μΌλ§ μ¤νƒ‘ κ³„μ‚° λ°©μ‹ μ„ νƒ"
    display_order: 1

    # UI λ§¤ν•‘
    display_mapping:
      "average_price_percent": "ν‰λ‹¨κ°€ λ€λΉ„ %p"
      "entry_price_percent": "μ§„μ…κ°€ λ€λΉ„ %p"
      "static_value_offset": "μ •μ  μ°¨μ΄κ°’"
      "percentage_of_tracked": "κ·Ήκ°’ λ€λΉ„ %"

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ μ¶”μ  κΈ°λ³Έλ³€μ (Tracked Variable) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  tracked_variable:
    # κΈ°λ³Έ μ •λ³΄
    parameter_name: "tracked_variable"
    parameter_type: "enum"
    default_value: "CURRENT_PRICE"
    is_required: true

    # μ„ νƒ μµμ…
    enum_values:
      - "CURRENT_PRICE"
      - "RSI"
      - "MACD"
      - "BOLLINGER_UPPER"
      - "BOLLINGER_LOWER"
      - "SMA_20"
      - "EMA_12"

    # ν‘μ‹ μ •λ³΄
    display_name_ko: "μ¶”μ  κΈ°λ³Έλ³€μ"
    display_name_en: "Tracked Variable"
    description: "νΈλ μΌλ§ν•  κΈ°λ³Έ λ³€μ μ„ νƒ"
    display_order: 2

    # UI λ§¤ν•‘
    display_mapping:
      "CURRENT_PRICE": "ν„μ¬κ°€"
      "RSI": "RSI μ§€ν‘"
      "MACD": "MACD μ§€ν‘"
      "BOLLINGER_UPPER": "λ³Όλ¦°μ € μƒλ‹¨"
      "BOLLINGER_LOWER": "λ³Όλ¦°μ € ν•λ‹¨"
      "SMA_20": "20μΌ λ‹¨μμ΄ν‰μ„ "
      "EMA_12": "12μΌ μ§€μμ΄ν‰μ„ "

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π’° κ³„μ‚°κ°’ (Value) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  value:
    # κΈ°λ³Έ μ •λ³΄
    parameter_name: "value"
    parameter_type: "decimal"
    default_value: "-2.0"
    is_required: true

    # μ μ•½ μ΅°κ±΄
    min_value: "-50.0"
    max_value: "50.0"

    # ν‘μ‹ μ •λ³΄
    display_name_ko: "κ³„μ‚°κ°’"
    display_name_en: "Value"
    description: "κ³„μ‚°μ— μ‚¬μ©λ  κ°’ (μμ: ν•λ½ μ΅°κ±΄, μ–‘μ: μƒμΉ μ΅°κ±΄)"
    display_order: 3

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π― μ¶”μ  λ°©ν–¥ (Trail Direction) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  trail_direction:
    # κΈ°λ³Έ μ •λ³΄
    parameter_name: "trail_direction"
    parameter_type: "enum"
    default_value: "down"
    is_required: true

    # μ„ νƒ μµμ…
    enum_values:
      - "up"      # μƒν–¥ μ¶”μ  (κ³ μ  μ¶”μ )
      - "down"    # ν•ν–¥ μ¶”μ  (μ €μ  μ¶”μ )

    # ν‘μ‹ μ •λ³΄
    display_name_ko: "μ¶”μ  λ°©ν–¥"
    display_name_en: "Trail Direction"
    description: "νΈλ μΌλ§ λ°©ν–¥ μ„¤μ •"
    display_order: 4

    # UI λ§¤ν•‘
    display_mapping:
      "up": "μƒν–¥ μ¶”μ  (κ³ μ β†’ν•λ½μ‹ νΈ)"
      "down": "ν•ν–¥ μ¶”μ  (μ €μ β†’μƒμΉμ‹ νΈ)"

# β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
# π“ λ§¤κ°λ³€μ μ΅°ν•© κ·μΉ™
# β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
parameter_validation:
  # μ΅°ν•© κ·μΉ™
  combination_rules:
    - name: "calculation_method_value_matching"
      description: "κ³„μ‚° λ°©μ‹μ— λ”°λ¥Έ μ μ ν• κ°’ λ²”μ„"
      rule: "percentage methods should use values between -100 and 100"

    - name: "direction_value_logic"
      description: "λ°©ν–¥κ³Ό κ°’μ λ…Όλ¦¬μ  μΌμΉμ„±"
      rule: "up direction typically uses negative values, down uses positive"

  # κ²½κ³  μ΅°κ±΄
  warnings:
    - condition: "abs(value) > 20"
      message: "λ„λ¬΄ ν° κ°’μ€ μ‹ νΈκ°€ λ°μƒν•μ§€ μ•μ„ μ μμµλ‹λ‹¤"

    - condition: "tracked_variable != 'CURRENT_PRICE' and calculation_method in ['average_price_percent', 'entry_price_percent']"
      message: "κ°€κ²© κΈ°μ¤€ κ³„μ‚°μ€ ν„μ¬κ°€ μ¶”μ μ‹ κ¶μ¥λ©λ‹λ‹¤"

# β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
# π¨ UI ν‘μ‹ μ„¤μ •
# β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
ui_settings:
  parameter_layout: "vertical"

  calculation_method:
    widget_type: "combobox"
    group_separator: true
    groups:
      price_based: ["average_price_percent", "entry_price_percent"]
      value_based: ["static_value_offset", "percentage_of_tracked"]

  tracked_variable:
    widget_type: "combobox"
    group_separator: true
    groups:
      price: ["CURRENT_PRICE"]
      indicators: ["RSI", "MACD"]
      bands: ["BOLLINGER_UPPER", "BOLLINGER_LOWER"]
      moving_averages: ["SMA_20", "EMA_12"]

  value:
    widget_type: "doublespinbox"
    step_size: 0.1
    suffix_by_method:
      "average_price_percent": "%p"
      "entry_price_percent": "%p"
      "static_value_offset": "μ›"
      "percentage_of_tracked": "%"

  trail_direction:
    widget_type: "radiobutton"
    layout: "horizontal"
  # β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•
  # π― UnifiedParameter κµ¬μ΅° - μ™Έλ¶€ μ μ–΄ν• μƒνƒ λ³€μ μ§€μ›
  # β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•β•

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ κ³„μ‚° λ°©μ‹ (Calculation Method) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "calculation_method"
    type: "enum"
    default_value: "percentage_of_tracked"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "average_price_percent"      # ν‰λ‹¨κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p) - ν‰λ‹¨κ°€ κΈ°μ¤€
      - "entry_price_percent"        # μ§„μ…κ°’ νΌμ„ΌνΈν¬μΈνΈ (%p) - μ§„μ…κ°€ κΈ°μ¤€
      - "static_value_offset"        # μ •μ μ°¨μ΄ (μ›ν™”/μμΉ) - μ λ€κ°’ μ°¨μ΄
      - "percentage_of_tracked"      # κ·Ήκ°’ λΉ„μ¨νΌμ„ΌνΈ (%) - μµκ³ /μµμ €μ  λ€λΉ„
    display_name: "κ³„μ‚° λ°©μ‹"
    description: "νΈλ μΌλ§ μ¤νƒ‘ κ³„μ‚° λ°©μ‹ (ν‰λ‹¨κ°€%p/μ§„μ…κ°€%p/μ •μ μ°¨μ΄/κ·Ήκ°’λΉ„μ¨%)"
    display_order: 1

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π“ μ¶”μ  κΈ°λ³Έλ³€μ (Tracked Variable) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "tracked_variable"
    type: "enum"
    default_value: "CURRENT_PRICE"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "CURRENT_PRICE"     # ν„μ¬κ°€ (μ‹¤μ‹κ°„)
      - "RSI"               # RSI μ§€ν‘
      - "MACD"              # MACD μ§€ν‘
      - "BOLLINGER_UPPER"   # λ³Όλ¦°μ € μƒλ‹¨
      - "BOLLINGER_LOWER"   # λ³Όλ¦°μ € ν•λ‹¨
      - "SMA_20"            # 20μΌ λ‹¨μμ΄ν‰μ„ 
      - "EMA_12"            # 12μΌ μ§€μμ΄ν‰μ„ 
    display_name: "μ¶”μ  κΈ°λ³Έλ³€μ"
    description: "νΈλ μΌλ§ν•  κΈ°λ³Έ λ³€μ μ„ νƒ (ν„μ¬κ°€, μ§€ν‘ λ“±)"
    display_order: 2

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # οΏ½ κ³„μ‚°κ°’ (Value) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "value"
    type: "decimal"
    default_value: "-2.0"
    required: true
    min_value: "-50.0"
    max_value: "50.0"
    enum_values: null
    display_name: "κ³„μ‚°κ°’"
    description: "κ³„μ‚°μ— μ‚¬μ©λ  κ°’ (νΌμ„ΌνΈ: -2.0=-2%, μ›ν™”: 1000=1000μ›)"
    display_order: 3

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # π― μ¶”μ  λ°©ν–¥ (Trail Direction) - ν•„μ λ§¤κ°λ³€μ
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "trail_direction"
    type: "enum"
    default_value: "down"
    required: true
    min_value: null
    max_value: null
    enum_values:
      - "up"      # μƒν–¥ μ¶”μ  (κ³ μ  μ¶”μ , ν•λ½ μ‹ μ‹ νΈ)
      - "down"    # ν•ν–¥ μ¶”μ  (μ €μ  μ¶”μ , μƒμΉ μ‹ μ‹ νΈ)
    display_name: "μ¶”μ  λ°©ν–¥"
    description: "νΈλ μΌλ§ λ°©ν–¥ (UP: κ³ μ μ¶”μ β†’ν•λ½μ‹ νΈ, DOWN: μ €μ μ¶”μ β†’μƒμΉμ‹ νΈ)"
    display_order: 4

  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  # β οΈ νƒ€μ„ν”„λ μ„ (Timeframe) - μ¶”μ λ³€μ λ”°λ¦„ (μ •λ³΄μ©)
  # β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€β”€
  - name: "timeframe"
    type: "enum"
    default_value: "follow_tracked_variable"
    required: false
    min_value: null
    max_value: null
    enum_values:
      - "follow_tracked_variable"    # μ¶”μ  λ³€μμ νƒ€μ„ν”„λ μ„ λ”°λ¦„ (κΈ°λ³Έ)
      - "realtime"                   # μ‹¤μ‹κ°„ (ν„μ¬κ°€μ©)
    display_name: "νƒ€μ„ν”„λ μ„"
    description: "μ¶”μ  λ³€μμ νƒ€μ„ν”„λ μ„μ„ λ”°λ¦„ (λ³„λ„ μ„¤μ • λ¶ν•„μ”)"
    display_order: 5
