# ═══════════════════════════════════════════════════════════════
# RSI 지표 (수정됨) (RSI) - 파라미터 파일
# ═══════════════════════════════════════════════════════════════

parameters:
  - name: "period"
    display_name: "기간"
    type: "int"
    default_value: 14
    min_value: 1
    max_value: 200
    step_value: 1
    description: "계산에 사용할 기간"
    tooltip: "값이 클수록 더 안정적이지만 느린 반응을 보입니다"
    required: true
    sort_order: 1

# 메타 정보
variable_info:
  parameter_required: true
  calculation_type: "technical_indicator"
  update_frequency: "realtime"
